logging:
  level:
    root: info
    com.cloud: debug
  file: logs/${spring.application.name}.log
  
spring:
  orgCodeHeader: orgCode                            #orgCode HTTP header name
  general:                                          #通用默认配置，目前仅支持两项，具体机构数据源可覆盖通用配置 
    maxPoolSize: 10                                 #数据源连接池最大连接数
    minIdle: 3                                      #数据源连接池最小idle数 
    defaultTenant : jg3                             #默认数据源，可设置为一个空的database，仅供Spring cloud检查数据源的可连接性 
  tenants:                                          #具体机构的数据源配置
    db0:
      url: jdbc:mysql://192.168.2.129:3306/cloud_user?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
      userName: root
      password: nw2018
    db2:
      url: jdbc:mysql://192.168.2.129:3306/cloud_user01?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
      userName: root
      password: nw2018
    db3:
      url: jdbc:mysql://192.168.2.129:3306/cloud_user02?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
      userName: root
      password: nw2018
      maxPoolSize: 20                               #覆盖默认配置 
      minIdle: 6                                    #覆盖默认配置
    db4:
      url: jdbc:mysql://192.168.2.129:3306/cloud_user03?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
      userName: root
      password: nw2018
  
#    datasource:
#      driver-class-name: com.mysql.jdbc.Driver
#      url: 
#      username: root
#      password: nw2018
#      hikari:
#        minimum-idle: 5
#        maximum-pool-size: 20
#        connection-test-query: SELECT 1
  rabbitmq:
    host: 192.168.2.129
    port: 5672
    username: nw
    password: nw2019
    virtual-host: /
  redis:
    host: 192.168.2.188
    port: 6379
    password: 123456
    timeout: 20s
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms
  mvc:
    servlet:
      load-on-startup: 1
  aop:
    proxy-target-class: true
  zipkin:
    base-url: http://192.168.2.129:9411
    enabled: true
    sender:
      type: web
mybatis:
  type-aliases-package: com.cloud.model.user
  mapper-locations: classpath:/mybatis-mappers/*
  configuration:
    mapUnderscoreToCamelCase: true
security:
  oauth2:
    resource:
      user-info-uri: http://192.168.2.193:8080/api-o/user-me
      prefer-token-info: false
wechat:
  domain: http://localhost:8080/api-u
  infos:
    app1:
      appid: xxx
      secret: xxx
    app2:
      appid: xxx
      secret: xxx
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
